# This is a basic workflow to help you get started with Actions

name: Deploy Docs

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      dest:
        description: 'destination subdirectory on a publishing branch'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14.x'
          
      - uses: bahmutov/npm-install@v1

      # Runs a single command using the runners shell
      - name: Install JS dependencies
        run:  yarn install

      # Runs a set of commands using the runners shell
      - name: Build
        run: VUEPRESS_BASE=/ yarn run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.vuepress/dist
          destination_dir: ${{ github.event.inputs.dest }}
